# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://daidieu.com" # the base hostname & protocol for your site
enforce_ssl: www.daidieu.com

# Build settings
markdown: kramdown
